version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo "hello"
      
workflows:
  version: 2 
  workflow-1:
    when:
      - not: <<$CIRCLE_PR_NUMBER>>
    jobs:
      - build
  workflow-2:
    when:
      - not: <<echo $CIRCLE_PR_NUMBER>>
    jobs:
      - build
  workflow-3:
    when:
      - equal: [master, <<$CIRCLE_BRANCH>>]
    jobs:
      - build
